hard_tabs = true
# ^^ this forces to use hard tabs instead of using spaces. Src: https://rust-lang.github.io/rustfmt/?version=v1.4.38&search=#hard_tabs

# tab_spaces = 4
# ^^ this has no effect if you choose ```hard_tabs = true```.
# Actally I am using some settings, you can check those in ```.vscode/settings.json``` file.

# learn using modules in rust i.e., code splitting things!, yikes!!

# Documentation at =>  https://rust-lang.github.io/rustfmt/?version=v1.4.36&search=#tab_spaces

# rustfmt is an official formatter from rust only, yikes!
# Rust analyzer extension reads this rustfmt.toml file to format the code of any .rs file in this project. Source: https://github.com/rust-analyzer/rust-analyzer/issues/1191#issuecomment-1018662166
# LEARN: You can use ```rustfmt <fileName>``` to format a file.

# You can run format via cli with `rustfmt fileName` too.
# .toml language: https://en.wikipedia.org/wiki/TOML

# Also added the same .rustfmt.toml file to global config place i.e., @ "C:\Users\chetan\AppData\Roaming\rustfmt\.rustfmt.toml".
